language: node_js
node_js:
  - "10"
cache: npm

notifications:
  email: false

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

after_script:
  - git checkout gh-pages
  - mkdir tmp
  - mv * tmp
  - mv tmp/_book/* .
  - rm -r tmp
  - git add -A
  - git commit -m "Updated By Travis-CI With Build $TRAVIS_BUILD_NUMBER For Github Pages"
  - git push "https://${TOKEN}@${REF}" gh-pages:gh-pages

branches:
  only:
    - src

env:
  global:
    - REF=github.com/gzrjzcx/Pointer2SSP.git # 设置 github 地址